<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use App\Support\NumericInput;

class StoreProductRequest extends FormRequest
{
    public function authorize(): bool
    {
        return auth()->check()
            && (bool) auth()->user()->is_admin;
    }

    protected function prepareForValidation(): void
    {
        $data = [
            'name' => $this->trimValue($this->input('name')),
            'slug' => $this->trimValue($this->input('slug')),
            'short_description' => $this->trimValue($this->input('short_description')),
            'description' => $this->trimValue($this->input('description')),
            'meta_title' => $this->trimValue($this->input('meta_title')),
            'meta_description' => $this->trimValue($this->input('meta_description')),
            'sku' => $this->trimValue($this->input('sku')),
            'size' => $this->trimValue($this->input('size')),
            'color' => $this->trimValue($this->input('color')),
            'color_code' => $this->trimValue($this->input('color_code')),
            'price' => NumericInput::normalize($this->input('price')),
            'sale_price' => NumericInput::normalize($this->input('sale_price')),
        ];

        $price = $data['price'];
        $salePrice = $data['sale_price'];

        /*
        |--------------------------------------------------------------------------
        | Friendly sale price handling
        |--------------------------------------------------------------------------
        |
        | If sale price is equal to or greater than the main price,
        | there is no real discount, so we simply ignore it.
        |
        */

        if (
            is_numeric($price) &&
            is_numeric($salePrice) &&
            (float) $salePrice >= (float) $price
        ) {
            $data['sale_price'] = null;
        }

        /*
        |--------------------------------------------------------------------------
        | Friendly color code handling
        |--------------------------------------------------------------------------
        */

        $colorCode = $data['color_code'] ?? null;

        if (
            $colorCode !== null &&
            $colorCode !== '' &&
            !preg_match(
                '/^#?[0-9A-Fa-f]{3}(?:[0-9A-Fa-f]{3})?$/',
                $colorCode
            )
        ) {
            $data['color_code'] = null;
        }

        $this->merge($data);
    }

    public function rules(): array
    {
        return [
            'category_id' => [
                'required',
                'integer',
                Rule::exists('categories', 'id')
                    ->whereNull('deleted_at'),
            ],

            'brand_id' => [
                'nullable',
                'integer',
                Rule::exists('brands', 'id')
                    ->whereNull('deleted_at'),
            ],

            'name' => [
                'bail',
                'required',
                'string',
                'max:180',
            ],

            /*
            |--------------------------------------------------------------------------
            | Slug can be generated automatically
            |--------------------------------------------------------------------------
            */

            'slug' => [
                'nullable',
                'string',
                'max:200',
                Rule::unique('products', 'slug'),
            ],

            'short_description' => [
                'nullable',
                'string',
                'max:1000',
            ],

            'description' => [
                'nullable',
                'string',
                'max:10000',
            ],

            'meta_title' => [
                'nullable',
                'string',
                'max:180',
            ],

            'meta_description' => [
                'nullable',
                'string',
                'max:320',
            ],

            /*
            |--------------------------------------------------------------------------
            | JSON is generated by the form.
            | We do not force the user to understand JSON.
            |--------------------------------------------------------------------------
            */

            'attributes_json' => [
                'nullable',
                'string',
            ],

            'is_active' => [
                'nullable',
                'boolean',
            ],

            'is_featured' => [
                'nullable',
                'boolean',
            ],

            'sort_order' => [
                'nullable',
                'integer',
                'min:0',
                'max:9999',
            ],

            /*
            |--------------------------------------------------------------------------
            | SKU can be generated automatically
            |--------------------------------------------------------------------------
            */

            'sku' => [
                'nullable',
                'string',
                'max:120',
                Rule::unique('product_variants', 'sku'),
            ],

            'size' => [
                'nullable',
                'string',
                'max:80',
            ],

            'color' => [
                'nullable',
                'string',
                'max:80',
            ],

            'color_code' => [
                'nullable',
                'string',
                'max:20',
            ],

            'price' => [
                'bail',
                'required',
                'numeric',
                'min:0',
                'max:999999999999.99',
            ],

            'sale_price' => [
                'nullable',
                'numeric',
                'min:0',
                'max:999999999999.99',
            ],

            'stock' => [
                'required',
                'integer',
                'min:0',
                'max:2147483647',
            ],

            'low_stock_threshold' => [
                'required',
                'integer',
                'min:0',
                'max:2147483647',
            ],

            'image_file' => [
                'nullable',
                'image',
                'mimes:jpeg,jpg,png,webp',
                'max:2048',
                'dimensions:max_width=1600,max_height=2000',
            ],
        ];
    }

    public function attributes(): array
    {
        return [
            'category_id' => 'دسته‌بندی',
            'brand_id' => 'برند',
            'name' => 'نام محصول',
            'slug' => 'اسلاگ محصول',
            'short_description' => 'توضیح کوتاه',
            'description' => 'توضیحات محصول',
            'meta_title' => 'عنوان سئو',
            'meta_description' => 'توضیحات سئو',
            'attributes_json' => 'ویژگی‌های محصول',
            'is_active' => 'وضعیت فعال بودن',
            'is_featured' => 'محصول ویژه',
            'sort_order' => 'ترتیب نمایش',
            'sku' => 'کد کالا',
            'size' => 'سایز',
            'color' => 'رنگ',
            'color_code' => 'رنگ',
            'price' => 'قیمت',
            'sale_price' => 'قیمت فروش ویژه',            'stock' => 'موجودی',
            'low_stock_threshold' => 'حد هشدار موجودی',
            'image_file' => 'تصویر محصول',
        ];
    }

    private function trimValue(mixed $value): mixed
    {
        return is_string($value)
            ? trim($value)
            : $value;
    }
}
